version: '3'

services:
  neo4j:
    image: neo4j:4.2.3
    restart: "always"
    networks:
      - ckg-network
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - DB_DUMP_FILE=ckg_latest_4.2.3.dump
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/import:/import
      - ./resources/neo4j_db/plugins:/var/lib/neo4j/plugins
      - ./resources/neo4j_db/load_data.sh:/docker-entrypoint.sh
      - ./resources/neo4j_db/neo4j.conf:/var/lib/neo4j/neo4j.conf

networks:
  ckg-network:
    external:
      name: knowledgebase-network