version: '3'

services:
  neo4j:
    image: neo4j:4.2.3
    restart: "always"
    networks:
      - ckg-network
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - DB_DUMP_FILE=ckg_latest_4.2.3.dump
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/import:/import
      - ./resources/neo4j_db/plugins:/var/lib/neo4j/plugins
      - ./resources/neo4j_db/load_data.sh:/docker-entrypoint.sh
      - ./resources/neo4j_db/neo4j.conf:/var/lib/neo4j/neo4j.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]
      interval: 30s
      timeout: 20s
      retries: 3

  ckg:
    image: ckg:202208281155
    container_name: "ckg"
    restart: "always"
    networks:
      - ckg-network
    links: 
      - neo4j
    depends_on: 
      - neo4j
    volumes:
      - ./data/example:/CKG/data
      - ./data/ckg_data/imports:/CKG/imports
      - ./data/ckg_data/downloads:/CKG/downloads
      - ./data/ckg_data/reports:/CKG/reports
      - ./docker_entrypoint.ckg.sh:/CKG/docker_entrypoint.sh
      - ./resources/connector_config.yml:/CKG/ckg/graphdb_connector/connector_config.yml
    expose:
      - "8090"
      - "8050"
      - "5000"
      - "6379"
    ports:
      # CKG prod
      - "8050:8050"
      # CKG dev
      - "5000:5000"
      # Redis
      - "6379:6379"
      # jupyterHub
      - "8090:8090"

networks:
  ckg-network:
    external:
      name: knowledgebase-network